openapi: 3.0.0
info:
  title: abi.storage Storage API
  version: '1.0'
servers:
  - url: 'https://api.abi.storage'
tags:
  - name: ABI Storage
paths:
  /upload:
    $ref: paths/upload.yaml
  /:
    $ref: paths.yaml
  '/{cid}':
    $ref: 'paths/{cid}.yaml'
  '/check/{cid}':
    $ref: 'paths/check@{cid}.yaml'
components:
  securitySchemes:
    bearerAuth:
      description: >
        The ABI Storage API uses *Bearer Tokens* to authenticate requests. You
        can view and manage your tokens in the [ABI Storage
        Dashboard](https://abi.storage).   


        Your tokens carry many privileges, so be sure to keep them secure! Do
        not share your *secret tokens* in publicly accessible areas such as
        GitHub, client-side code, and so forth.   


        **Bearer authentication** (also called token authentication) is an HTTP
        authentication scheme that involves security tokens called bearer
        tokens. The name “Bearer authentication” can be understood as “give
        access to the bearer of this token.” The bearer token is a cryptic
        string, usually generated by the server in response to a login request.
        The client must send this token in the Authorization header when making
        requests to protected resources:


        ```js

        Authorization: Bearer <token>

        ```
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
